Repository MicroFocus/hpaa-octane-dev, pull requests merged in 2018-09, with the labels that each got.

#115 improving processing of the workflow (aka pipeline-as-a-code) pipelines - structure, stages (JENKINS-53343)
  .gitignore
  pom.xml
  src/main/java/com/microfocus/application/automation/tools/octane/buildLogs/RunListenerForLogs.java
  src/main/java/com/microfocus/application/automation/tools/octane/events/ItemListenerImpl.java
  src/main/java/com/microfocus/application/automation/tools/octane/events/RunListenerImpl.java
  src/main/java/com/microfocus/application/automation/tools/octane/events/SCMListenerImpl.java
  src/main/java/com/microfocus/application/automation/tools/octane/events/WorkflowListener.java
  src/main/java/com/microfocus/application/automation/tools/octane/model/CIEventCausesFactory.java
  src/main/java/com/microfocus/application/automation/tools/octane/model/ModelFactory.java
  src/main/java/com/microfocus/application/automation/tools/octane/model/processors/parameters/DynamicParameterProcessor.java
  src/main/java/com/microfocus/application/automation/tools/octane/model/processors/parameters/ParameterProcessors.java
  src/main/java/com/microfocus/application/automation/tools/octane/tests/TestDispatcher.java
  src/main/java/com/microfocus/application/automation/tools/octane/tests/TestListener.java
  src/main/java/com/microfocus/application/automation/tools/octane/tests/build/BuildHandlerUtils.java
  src/main/java/com/microfocus/application/automation/tools/octane/tests/detection/TestNGExtension.java
  src/main/java/com/microfocus/application/automation/tools/octane/tests/impl/ObjectStreamIterator.java
  src/main/java/com/microfocus/application/automation/tools/octane/tests/junit/JUnitExtension.java
  src/main/java/com/microfocus/application/automation/tools/octane/workflow/BuildRelations.java
  src/main/java/com/microfocus/application/automation/tools/octane/workflow/WorkFlowUtils.java
  src/main/java/com/microfocus/application/automation/tools/octane/workflow/WorkflowBuildAdapter.java
  src/main/java/com/microfocus/application/automation/tools/octane/workflow/WorkflowGraphListener.java
  src/test/java/com/microfocus/application/automation/tools/octane/events/EventsTest.java
Labels: bug, enhancement

#117 user story #678027 : Create function that converts the testToRun to a parameter of a job
  pom.xml
  src/main/java/com/microfocus/application/automation/tools/octane/testrunner/TestsToRunConverterBuilder.java
  src/main/java/com/microfocus/application/automation/tools/octane/testrunner/TestsToRunConverterModel.java
  src/main/java/com/microfocus/application/automation/tools/octane/testrunner/VariableInjectionAction.java
  src/main/resources/com/microfocus/application/automation/tools/octane/testrunner/TestsToRunConverterBuilder/config.jelly
  src/main/resources/com/microfocus/application/automation/tools/octane/testrunner/TestsToRunConverterBuilder/help-framework.html
  src/main/resources/com/microfocus/application/automation/tools/octane/testrunner/TestsToRunConverterBuilder/help.html
Labels: enhancement

#121 defect #718030: fixing SRF/SRL/PC tests type detection (JENKINS-53674)
  src/main/java/com/microfocus/application/automation/tools/octane/CIJenkinsServicesImpl.java
  src/main/java/com/microfocus/application/automation/tools/octane/tests/TestListener.java
  src/main/java/com/microfocus/application/automation/tools/octane/tests/detection/UFTExtension.java
Labels: bug
